# Generated by Django 3.1.5 on 2021-01-29 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_auto_20210129_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='parent_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kb.section', verbose_name='Родительский раздел'),
        ),
    ]
