# Generated by Django 3.1.5 on 2021-01-29 15:58

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_auto_20210129_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=djrichtextfield.models.RichTextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=djrichtextfield.models.RichTextField(verbose_name='Текст комментария'),
        ),
    ]
