# Generated by Django 3.1.5 on 2021-01-29 16:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_auto_20210129_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст комментария'),
        ),
    ]
