# Generated by Django 3.1.5 on 2021-01-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0008_auto_20210129_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['section', 'name'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
