# Generated by Django 3.1.5 on 2021-01-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210121_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopUser',
            new_name='UserBalance',
        ),
    ]
