# Generated by Django 3.1.5 on 2021-01-21 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_auto_20210121_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='username',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
