# Generated by Django 3.1.5 on 2021-01-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210122_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
